#!/usr/bin/env python

import sys
import os.path

import fq_manifestor

if len(sys.argv) != 3:
    print('USAGE: fq-manifestor input-directory output-filepath')
    exit(0)

input_dir = sys.argv[1]
output_fp = sys.argv[2]

fq_manifestor.fq_manifestor(input_dir, output_fp)
output_fp = os.path.abspath(output_fp)

print("To import, try running:")
print("qiime tools import "\
      "--type 'SampleData[PairedEndSequencesWithQuality]' "\
      "--input-path %s --output-path demux.qza "\
      "--input-format PairedEndFastqManifestPhred33V2" % output_fp)
